### ISSUE TITLE
Emacs 25.2.2 doesn't work

### ISSUE THREAD

**Issue by blakemcbride** [cwfoo/emacs-batch-indent#1]
Greetings,

I discovered that your program does not work on GNU Emacs 25.2.2.

I upgraded to 27.1.  It does work with that.

Thanks!

Blake

**Comment by cwfoo** [comment]
Could you provide details of the errors you are getting? What is your OS?

I have just run the unit tests on GNU Emacs 25.2.2 in Ubuntu 18.04.2, and all the test cases are passing.

Perhaps I should set up automated tests for all GNU Emacs releases within the last 5 years (versions 25.1 to 27.2), since I occasionally use old versions too. I'll do that once I figure out how to set up Travis with 8 Emacs versions.

**Comment by cwfoo** [comment]
@blakemcbride Any updates on this? I have insufficient information to reproduce the problem.

**Comment by blakemcbride** [comment]
Sorry for the delay.  I've been using it and it works fine.  I don't remember what I did to fix the problem I was having.  Thanks!
